default_language_version:
  python: python3

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: check-json
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-toml
  - id: check-xml
  - id: detect-private-key
  - id: name-tests-test
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/codingjoe/relint
  rev: 0.5.0
  hooks:
    - id: relint
