- name: "Don't commit"
  pattern: "@?[dDsD][oO][nN][tT]_?[cC][oO][mM]{1,3}[iI][tT]"
  filename:
    - "*"
  error: true

#- name: My path
#  pattern: "/home/robert"
#  filename:
#      - "*"
#
#- name: My email
#  pattern: "robert\.wenner@"
#  filename:
#      - "*"

- name: Perl printf debugger
  pattern: "^print STDERR"
  filename:
     - "*.pl"
     - "*.pm"
     - "*.t"

- name: Java printf debugger
  pattern: "^System.(out|err).println\\("
  filename:
     - "*.java"

- name: Java IDE comments
  pattern: "// IDE generated stub"
  filename:
     - "*.java"
