language: perl
perl:
    - "5.26"
    - "5.14"
    - "5.10"
install:
    - cpanm --quiet --installdeps --notest . lib/ t/
    - cpanm --quiet --notest Devel::Cover
    - cpanm --quiet --notest Devel::Cover::Report::Coveralls
